version: '3.3'
services:
    grafana:
        container_name: grafana
        ports:
            - '3000:3000'
        image: grafana/grafana
        user: "$UID:$GID"
        environment:
            - 'GF_INSTALL_PLUGINS=grafana-strava-datasource,alexanderzobnin-zabbix-app'
        volumes:
            - ./data/grafana:/var/lib/grafana
